<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>tycho-its-project.surefire.uiharness.customapplication</groupId>
	<artifactId>tycho.its.surefire.uiharness.customapp</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>eclipse-test-plugin</packaging>

	<repositories>
		<repository>
			<id>platform</id>
			<url>${target-platform}</url>
			<layout>p2</layout>
		</repository>
	</repositories>

	<build>
		<plugins>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-maven-plugin</artifactId>
				<version>${tycho-version}</version>
				<extensions>true</extensions>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>target-platform-configuration</artifactId>
				<version>${tycho-version}</version>
				<configuration>
					<filters>
						<!-- an RCP target platform without the Eclipse IDE bundles -->
						<filter>
							<type>eclipse-plugin</type>
							<id>org.eclipse.ui.ide.application</id>
							<removeAll />
						</filter>
					</filters>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-surefire-plugin</artifactId>
				<version>${tycho-version}</version>
				<configuration>
					<useUIHarness>true</useUIHarness>
					<application>tycho.its.uiharness.customapp</application>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
