<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>tycho.its</groupId>
	<artifactId>tycho.test.bundlewithfragment.extraclasspath</artifactId>
	<version>1.0.0</version>
	<packaging>pom</packaging>
	<parent>
		<groupId>tycho.its</groupId>
		<artifactId>compiler.fragments2.extraclasspath.all</artifactId>
		<version>1.0.0</version>
		<relativePath>../pom.xml</relativePath>
	</parent>
	<modules>
		<module>tycho.test.host</module>
		<module>tycho.test.host.fragment</module>
	</modules>
</project>
