name: Build Tycho
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
on:
  push:
    branches: 
      - 'main'
      - 'tycho-*'
  pull_request:
    branches: 
     - 'main'
     - 'tycho-*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: Set up Java
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        java-version: |
            11
            17
            21
        distribution: 'temurin'
        cache: maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@12eb41b233df95d49b0c11fc1b5bc8312e5d4ce0 # v5.1
      with:
        maven-version: 3.9.16
    - name: Build Tycho
      env:
       JAVA_HOME: ${{ env.JAVA_HOME_21_X64 }}
      run: | 
        mvn -U -V -e -B -ntp clean install --file pom.xml -DtrimStackTrace=false -Pits -fae
    - name: Upload Test Results
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: always()
      with:
        name: test-results-${{ matrix.os }}
        if-no-files-found: warn
        path: |
          ${{ github.workspace }}/*/target/surefire-reports/TEST-*.xml
          ${{ github.workspace }}/*/*/target/surefire-reports/TEST-*.xml
          ${{ github.workspace }}/*/*/*/target/surefire-reports/TEST-*.xml
  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: Event File
        path: ${{ github.event_path }}

