# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Verify mwe Build
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
on:
  pull_request:
    branches: 
     - 'master'

jobs:
  build:
    name: mwe
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tycho code
      uses: actions/checkout@v3
      with:
       path: 'tycho'
    - name: Checkout platform code
      uses: actions/checkout@v3
      with:
       path: 'mwe'
       submodules: 'recursive'
       lfs: true
       repository: 'eclipse/mwe'
       fetch-depth: 0
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: |
            8
            11
            17
        distribution: 'adopt'
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-verify-platform-${{ hashFiles('**/pom.xml', '**/*.target') }}
        restore-keys: |
          ${{ runner.os }}-maven-verify-platform-
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.8.6
    - name: Build Tycho
      env:
       JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
      working-directory: 'tycho'
      run: >- 
        mvn -U -V -e -B -ntp
        -DskipTests
        --file pom.xml
        -T1C
        --global-toolchains ${{ github.workspace }}/tycho/.github/toolchains.xml
        clean install
    - name: Run mwe Build
      env:
       JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
      working-directory: 'mwe'
      run: >- 
        mvn -e -B -f maven/org.eclipse.emf.mwe2.parent/pom.xml
        -Dsign.skip=true 
        -DskipTests
        -Dmaven.javadoc.failOnError=false
        -Dtycho.localArtifacts=ignore
        -DBUILD_TYPE=N
        -Dtycho-version=3.1.0-SNAPSHOT
        clean verify
